# Generated by Django 6.0.2 on 2026-02-15 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(editable=False, help_text='Unique project identifier (auto-generated)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable project name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional project description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the project was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the project was updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this project is actively being tracked')),
                ('owner', models.ForeignKey(help_text='User who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='ses_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
