# Generated by Django 6.0.2 on 2026-02-15 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique forecast record identifier', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this forecast was computed')),
                ('forecast_next', models.FloatField(help_text='Predicted next health score')),
                ('forecast_window', models.IntegerField(default=10, help_text='Window size used for forecasting')),
                ('confidence_score', models.FloatField(help_text='Confidence score (0.0 - 1.0)')),
                ('confidence_interval_lower', models.FloatField(blank=True, help_text='Lower bound of confidence interval', null=True)),
                ('confidence_interval_upper', models.FloatField(blank=True, help_text='Upper bound of confidence interval', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root mean square error', null=True)),
                ('residual_variance', models.FloatField(blank=True, help_text='Variance of residuals', null=True)),
                ('volatility', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', help_text='Volatility classification', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('insufficient_data', 'Insufficient Data'), ('error', 'Error')], default='success', help_text='Forecast computation status', max_length=20)),
                ('project', models.ForeignKey(help_text='Project this forecast belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forecast_records', to='ses_api.project')),
            ],
            options={
                'verbose_name': 'Forecast Record',
                'verbose_name_plural': 'Forecast Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', '-timestamp'], name='ses_api_for_project_024da0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique health record identifier', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this health assessment was computed')),
                ('health_score', models.FloatField(help_text='Overall health score (0.0 - 1.0)')),
                ('stability_score', models.FloatField(blank=True, help_text='Stability component score', null=True)),
                ('complexity_score', models.FloatField(blank=True, help_text='Complexity component score', null=True)),
                ('coupling_score', models.FloatField(blank=True, help_text='Coupling component score', null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Current risk level', max_length=20)),
                ('risk_indicators', models.JSONField(default=list, help_text='List of active risk indicators')),
                ('raw_output', models.JSONField(default=dict, help_text='Full health computation output')),
                ('project', models.ForeignKey(help_text='Project this health record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='ses_api.project')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', '-timestamp'], name='ses_api_hea_project_56dcde_idx'), models.Index(fields=['project', '-health_score'], name='ses_api_hea_project_4ad5de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique snapshot identifier', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was captured')),
                ('node_count', models.IntegerField(default=0, help_text='Number of nodes in the call graph')),
                ('edge_count', models.IntegerField(default=0, help_text='Number of edges in the call graph')),
                ('raw_data', models.JSONField(default=dict, help_text='Raw snapshot data (call graph, metrics, etc.)')),
                ('edge_signature', models.JSONField(default=dict, help_text='Edge signature for change detection')),
                ('project', models.ForeignKey(help_text='Project this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ses_api.project')),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', '-timestamp'], name='ses_api_sna_project_da7397_idx')],
            },
        ),
    ]
